package com.leonet.eclub.base

import com.leonet.eclub.di.DaggerAppComponent
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication

/**
 * Initialization of libraries.
 */
class BaseApplication : DaggerApplication() {

    override fun onCreate() {
        super.onCreate()

    }
    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [com.leo.msw.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.builder().create(this)
    }
}
